# Generated by Django 4.2 on 2024-11-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_alter_city_options_alter_city_ct_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lan_name', models.CharField(max_length=50, unique=True, verbose_name='Язык программирования')),
                ('lan_slug', models.SlugField(blank=True, unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Язык программирования',
                'verbose_name_plural': 'Языки программирования',
            },
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Название населенного пункта', 'verbose_name_plural': 'Название населенных пунктов'},
        ),
        migrations.AlterField(
            model_name='city',
            name='ct_name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название населенного пункта'),
        ),
    ]
